version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "5000:5000"
    depends_on:
      - db
      - service

  service:
    build: ./service
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "5432:5432"

networks:
  mytube:
