version: '3.8'

services:
  app:
    platform: linux/amd64
    image: ${COMPOSE_PROJECT_NAME}-app
    build: ./app
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "5000:5000"
    depends_on:
      - db
      - service

  service:
    platform: linux/amd64
    image: ${COMPOSE_PROJECT_NAME}-service
    build: ./service
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: ${COMPOSE_PROJECT_NAME}-db
    build: ./db
    env_file:
      - .env
    networks:
      - mytube
    ports:
      - "5432:5432"

networks:
  mytube:
