version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db712bccc14d602212c928a39ba7e23d
    networks:
      - yourtube
    ports:
      - "5432:5432"

networks:
  yourtube:
