apiVersion: v1
kind: Service
metadata:
  name: mytube-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: mytube-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
