apiVersion: v1
kind: Service
metadata:
  name: mytube-app-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: mytube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
