apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      initContainers:
      - name: app-init
        image: {{ .Values.app_repository_url }}:{{ .Values.app_version }}
        command: ['make', 'init-db']
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: credentials
        {{- include "mytube.envvars" . | indent 8}}
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: app
        image: {{ .Values.app_repository_url }}:{{ .Values.app_version }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: credentials
        {{- include "mytube.envvars" . | indent 8}}
        ports:
        - name: http
          containerPort: 5000
      nodeSelector:
        kubernetes.io/os: linux
