apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db_name }}-deployment
  namespace: mytube
  labels:
    app: {{ .Values.db_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db_name }}
    spec:
      containers:
      - name: db
        #image: 471976620771.dkr.ecr.sa-east-1.amazonaws.com/mytube-db:latest
        image: {{ .Values.db_name }}:{{ .Values.db_version }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: credentials
        ports:
        - name: http
          containerPort: 3000
      nodeSelector:
        kubernetes.io/os: linux
