apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service_name }}
    spec:
      initContainers:
      - name: service-init
        command: ['make', 'init-db']
        image: {{ .Values.service_repository_url }}:{{ .Values.service_version }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: credentials
        {{- include "mytube.envvars" . | indent 8}}
      containers:
      - name: service
        image: {{ .Values.service_repository_url }}:{{ .Values.service_version }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: credentials
        {{- include "mytube.envvars" . | indent 8}}
        ports:
        - name: http
          containerPort: 3000
      nodeSelector:
        kubernetes.io/os: linux
