apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service_name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
